import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased h-screen flex flex-col`}>
        <StoreProvider>
          <Header />
          <div className="flex-1 w-full flex flex-col self-center max-w-[1440px]">
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
